### ISSUE TITLE
DUS: Error in `db_copy_to()` at dbplyr/R/verb-copy-to.R:83:5:

### ISSUE THREAD

**Issue by Elyne** [oxford-pharmacoepi/MegaStudy#63]
Hi team,

I am running the DUS code, in the version [DUS_1point4.zip] given in response to @filipmaljkovic (I was getting the same error as him).

Now, I am getting following errors during "GENERATE DRUG CONCEPTS":

Created a temporary table named #dbplyr_f7dup4XPTw
Error in `db_copy_to()` at dbplyr/R/verb-copy-to.R:83:5:
! Can't copy data to table "#dbplyr_f7dup4XPTw".
Caused by error in `dplyr::db_write_table()` at dbplyr/R/db-io.R:79:7:
! Can't write table table "#dbplyr_f7dup4XPTw".
Caused by error in `name@name[["table"]]`:
! subscript out of bounds
Backtrace:
     ▆
  1. ├─base::source(here("DUS.R"))
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. ├─base::source(here("drugs.R"))
  6. │ ├─base::withVisible(eval(ei, envir))
  7. │ └─base::eval(ei, envir)
  8. │   └─base::eval(ei, envir)
  9. ├─CodelistGenerator::getDrugIngredientCodes(...)
 10. │ └─CodelistGenerator:::fetchBatchedDescendants(...) at CodelistGenerator/R/drugCodes.R:226:5
 11. │   └─CodelistGenerator::getDescendants(...) at CodelistGenerator/R/drugCodes.R:309:5
 12. │     └─CodelistGenerator:::getDescendantsAndAncestor(...) at CodelistGenerator/R/vocabUtilities.R:353:5
 13. │       └─... %>% dplyr::left_join(cdm$concept, by = "concept_id") at CodelistGenerator/R/vocabUtilities.R:394:3
 14. ├─dplyr::left_join(., cdm$concept, by = "concept_id") at magrittr/R/pipe.R:136:3
 15. ├─dplyr::rename(., concept_id = "descendant_concept_id") at dplyr/R/join.R:300:3
 16. ├─dplyr::inner_join(...) at dplyr/R/rename.R:64:3
 17. ├─omopgenerics:::inner_join.cdm_table(...) at dplyr/R/join.R:258:3
 18. │ ├─dplyr::inner_join(x, ...) at omopgenerics/R/overwriteClasses.R:137:3
 19. │ └─dbplyr:::inner_join.tbl_lazy(x, ...) at dplyr/R/join.R:258:3
 20. │   └─dbplyr:::add_join(...) at dbplyr/R/verb-joins.R:89:3
 21. │     ├─dplyr::auto_copy(x, y, copy = copy, indexes = if (auto_index) list(by$y)) at dbplyr/R/verb-joins.R:356:3
 22. │     └─dbplyr:::auto_copy.tbl_sql(x, y, copy = copy, indexes = if (auto_index) list(by$y)) at dplyr/R/copy-to.R:59:3
 23. │       ├─dplyr::copy_to(...) at dbplyr/R/verb-copy-to.R:103:3
 24. │       └─dbplyr:::copy_to.src_sql(...) at dplyr/R/copy-to.R:32:3
 25. │         ├─dbplyr::db_copy_to(...) at dbplyr/R/verb-copy-to.R:83:5
 26. │         └─dbplyr:::db_copy_to.DBIConnection(...) at dbplyr/R/db-io.R:54:3
 27. │           ├─dbplyr:::with_transaction(...) at dbplyr/R/db-io.R:74:3
 28. │           │ └─base::withCallingHandlers(...) at dbplyr/R/db-io.R:233:3
 29. │           ├─dplyr::db_write_table(...) at dbplyr/R/db-io.R:79:7
 30. │           └─dbplyr:::db_write_table.DBIConnection(...) at dplyr/R/dbplyr.R:90:3
 31. │             ├─base::withCallingHandlers(...) at dbplyr/R/db-io.R:189:3
 32. │             ├─DBI::dbWriteTable(...) at dbplyr/R/db-io.R:189:3
 33. │             └─odbc::dbWriteTable(...) at DBI/R/13-dbWriteTable.R:49:9
 34. │               └─odbc (local) .local(conn, name, value, ...)
 35. │                 ├─DBI::dbExistsTable(conn, name) at odbc/R/Table.R:54:5
 36. │                 └─odbc::dbExistsTable(conn, name)
 37. │                   ├─DBI::dbExistsTable(...) at odbc/R/Table.R:223:5
 38. │                   └─odbc::dbExistsTable(...)
 39. │                     └─name@name[["table"]] %in% ... at odbc/R/Table.R:210:5
 40. └─dbplyr (local) `<fn>`(`<sbscOOBE>`) at odbc/R/Table.R:210:5
 41.   └─cli::cli_abort(msg, parent = cnd) at dbplyr/R/db-io.R:202:7
 42.     └─rlang::abort(...) at cli/R/rlang.R:45:3
Execution halted

Any idea how to circumvent? Attaching the log itself as well.

[MEGA_log.txt](https://github.com/user-attachments/files/15791287/MEGA_log.txt)

**Comment by tiozab** [comment]
hi @Elyne. thanks! with which database management system do you work? We have another open issue from you, has that been resolved? https://github.com/oxford-pharmacoepi/MegaStudy/issues/25

**Comment by Elyne** [comment]
I have made a snapshot of our database and migrated it to Microsoft SQL Server to be able to run the IncidencePrevalence step. We have run that succesfully on the new database but were unable to finally run the code on Spark. I understood from the issue that it was a problem with underlying packages that do not support Spark completely.

For DUS, we also use the SQL server snapshot.

**Comment by Elyne** [comment]
I used the code provided to #53 , so i'm running dbplyr==2.5.0. I was having the same cohort overlap-issues as filip. What I am thinking is that I might want to generate the cohorts with that specific version, serialize as RData, and then continue on with the published version where older packages are used. Would that be viable?

**Comment by tiozab** [comment]
@elyne that is Worth a Shot.

**Comment by tiozab** [comment]
Thanks @Elyne I think having the incident patients is already a success! Do I understand correctly that you have the results until [line 486](https://github.com/oxford-pharmacoepi/MegaStudy/blob/main/DUS%20Code/DUS.R#L486) ?

**Comment by Elyne** [comment]
I have results until line 594; the latest file I have is prev_demographics_summary_MEGA.csv.

**Comment by tiozab** [comment]
ok, great I suggest you upload that and I see whether I can get more information on what to do about that error from maintainers (always valuable information for them to see how databases react to their packages), also this seems to be more of a generic error.
@ablack3 @edward-burn @catalamarti

**Comment by Elyne** [comment]
I have fixed it, I have been able to run the code twice, resulting in a zip file.

By processing individual_indications, drugs.R, and the covid variable in "GENERATE INDICATION COHORTS" beforehand and writing them to RData files, I think I was able to eliminate the lingering connection that deadlocked during the prevalence stage. The error is indeed quite generic and has to do with the R-script (and packages)'s interaction with the (specific) database.

      #source(here("individual_indications.R"))
      load("individual_indications.RData")
      
      #source(here("drugs.R"))
      load("drugs.RData")
      
      save("covid"), file = "cdm_covid.RData")
      load("cdm_covid.RData")

Thank you for looking into this, and also to other people that log their issues. It provides a lot of context and information how to troubleshoot!

**Comment by tiozab** [comment]
@Elyne fantastic!! I guess I did not do much. Thanks! Also good to know in case others run into the same problem.

**Comment by eric-fey-hus** [comment]
@Elyne how did you solve your original problem:
```R
Created a temporary table named #dbplyr_f7dup4XPTw
Error in db_copy_to() at dbplyr/R/verb-copy-to.R:83:5:
! Can't copy data to table "#dbplyr_f7dup4XPTw".
Caused by error in dplyr::db_write_table() at dbplyr/R/db-io.R:79:7:
! Can't write table table "#dbplyr_f7dup4XPTw".
Caused by error in name@name[["table"]]:
! subscript out of bounds
```
?
I used fix  [DUS_1point4.zip]  and changed to CDMConnector-1.5.0, but still getting the same error.

**Comment by Elyne** [comment]
I see in the other thread you have found it already. :) The package versions indeed need very specific versions. I had also serialized parts of the results with certain package types instead of running in one go.

**Comment by tiozab** [comment]
thank you @Elyne :-)
